name: Pipeline

on:
  push:
    branches:
      - master
      - develop
      
jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'

    - name: Run tests
      run: |
          cd ./back
          go clean -testcache
          go test ./internal/server/handler ./internal/services/commander

  check:
    name: Check changed files
    needs: test
    if: ${{ needs.test.result == 'success' }}
    outputs:
      executor: ${{ steps.check_files.outputs.executor }}
      frontend: ${{ steps.check_files.outputs.frontend }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
            echo "=============== list modified files ==============="
            git diff --name-only HEAD^ HEAD

            echo "========== check paths of modified files =========="
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == back/* ]]; then
                echo "::set-output name=executor::true"
              elif [[ $file == front/* ]]; then
                echo "::set-output name=frontend::true"
              else
                echo "file does not belong to any service"
              fi
            done < files.txt

  executor:
    name: Deploy Backend
    needs: check
    if: needs.check.outputs.executor == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: enchik0reo/script_executor.backend:0.0.${{ github.run_id }}

    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts

    - name: Copy db script
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir -p ./back/scripts"
        scp ./back/scripts/1_init.up.sql ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:./back/scripts

    - name: Create env
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cat << EOF > .env
        IMAGE_TAG=${{ github.run_id }}
        EOF"

    - name: Copy docker compose config
      run: scp ./back/docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:docker-compose-back.yml

    - name: Compose down and up
      run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "docker-compose -f docker-compose-back.yml down && docker-compose -f docker-compose-back.yml up -d && exit"

  frontend:
    name: Deploy Frontend
    needs: check
    if: needs.check.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        context: ./front
        push: true
        tags: enchik0reo/script_executor.frontend:0.0.${{ github.run_id }}

    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts

    - name: Create env
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cat << EOF > .env
        IMAGE_TAG=${{ github.run_id }}
        EOF"

    - name: Copy docker compose config
      run: scp ./front/docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:docker-compose-front.yml

    - name: Compose down and up
      run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "docker-compose -p react -f docker-compose-front.yml down && docker-compose -p react -f docker-compose-front.yml up -d && exit"
